Repository strongbox/ci-build-images, pull requests merged in 2020-10, with the labels that each got.

#15 Upgrading from node 12 to 14 (latest LTS)
  Jenkinsfile
  images/alpine/jdk11/Dockerfile.alpine.jdk11-mvn3.6-mono5
  images/alpine/jdk11/Dockerfile.alpine.jdk11-mvn3.6-mono5-nuget3.4-choco0.10
  images/alpine/jdk11/Dockerfile.alpine.jdk11-mvn3.6-node14
  images/alpine/jdk8/Dockerfile.alpine.jdk8-mvn3.6-mono5
  images/alpine/jdk8/Dockerfile.alpine.jdk8-mvn3.6-mono5-nuget3.4-choco0.10
  images/alpine/jdk8/Dockerfile.alpine.jdk8-mvn3.6-node14
  images/opensuse/Dockerfile.opensuse
  images/ubuntu/jdk11/Dockerfile.ubuntu.jdk11-mvn3.6-node14-browsers
  images/ubuntu/jdk8/Dockerfile.ubuntu.jdk8-mvn3.6-node14-browsers
Labels: GraceHopperOSD

#19 Issue 1829: Upgrade to latest version of Nuget
  images/alpine/jdk11/Dockerfile.alpine.jdk11-mvn3.6-mono5-nuget5.7
  images/alpine/jdk8/Dockerfile.alpine.jdk8-mvn3.6-mono5-nuget5.7
Labels: hacktoberfest

#22 Issue 1830: Upgrade the version of SBT in strongbox-web-integration to the 1.3.13
  common-scripts/setup-sbt.sh
  images/alpine/jdk11/Dockerfile.alpine.jdk11-mvn3.6-sbt1.3
  images/alpine/jdk8/Dockerfile.alpine.jdk8-mvn3.6-sbt1.3
Labels: hacktoberfest, hacktoberfest-accepted
